### ISSUE TITLE
Setup help please

### ISSUE THREAD

**Issue by BeFranke** [Hatmm/PED-DETR-for-Pedestrian-Detection#2]
Hello, 
I am really interested in trying out your framework. Could you elaborate a little bit more on the installation process please?
I did install Detectron2 and Fast-Transformer, but what should I do with DETR and Deformable-DETR, as you can't really install those as packages to your environment? Are these supposed to be added as submodules?
Thank you for your time.

**Comment by Hatmm** [comment]
Hi sorry, configs for running DQRF will be uploaded. You don't need Fast-Transformer module, as you can see here https://github.com/Hatmm/PED-DETR-for-Pedestrian-Detection/blob/20e3046a0a0701834befa4657e7db6b66adc9401/dqrf/ops/functions/local_attn.py#L156 you can obtain similar behavior by multiplying the weights of the self attention module by a binary mask where 1 correspond to the 100 nearest keys for each query. To train, don't forget to first convert you json using our provided code, then you can simply run train_net and specify the number of gpu and the path for you config for instance python $ROOT/train_net.py \
  --num-gpus $NUM_GPUS \
  --config-file $ROOT/configs/file.yaml
